"""Structured domain events generated by runtime subsystems."""

from dataclasses import dataclass

from astraloop.mission.modes import MissionMode


@dataclass(frozen=True, slots=True)
class MissionTransitionEvent:
    tick: int
    time: float
    from_state: MissionMode
    to_state: MissionMode
    reason_code: str
    message: str
