"""Structured domain events generated by runtime subsystems."""

from dataclasses import dataclass
from enum import StrEnum

from astraloop.mission.modes import MissionMode


@dataclass(frozen=True, slots=True)
class MissionTransitionEvent:
    tick: int
    time: float
    from_state: MissionMode
    to_state: MissionMode
    reason_code: str
    message: str


class FaultEventType(StrEnum):
    ACTIVATED = "activated"
    DEACTIVATED = "deactivated"


@dataclass(frozen=True, slots=True)
class FaultLifecycleEvent:
    tick: int
    time: float
    fault_id: str
    fault_type: str
    target: str
    event_type: FaultEventType
